CREATE EXTENSION IF NOT EXISTS postgis;

create sequence if not exists chat_message_file_id_seq;
create sequence if not exists chat_message_id_seq;
create sequence if not exists chat_room_id_seq;
create sequence if not exists chat_room_member_id_seq;

create sequence if not exists domain_image_seq increment by 50;
create sequence if not exists group_auth_code_seq increment by 50;
create sequence if not exists group_member_seq increment by 50;
create sequence if not exists group_seq increment by 50;
create sequence if not exists image_seq increment by 50;
create sequence if not exists member_oauth_account_seq increment by 50;
create sequence if not exists member_seq increment by 50;
create sequence if not exists refresh_token_seq increment by 50;
create sequence if not exists subgroup_member_seq increment by 50;
create sequence if not exists subgroup_seq increment by 50;

create sequence if not exists ai_restaurant_comparison_id_seq;
create sequence if not exists ai_restaurant_recommendation_id_seq;
create sequence if not exists ai_restaurant_review_analysis_id_seq;

create sequence if not exists announcement_id_seq;
create sequence if not exists food_category_id_seq;
create sequence if not exists image_optimization_job_id_seq;
create sequence if not exists keyword_id_seq;
create sequence if not exists member_favorite_restaurant_id_seq;
create sequence if not exists member_notification_preference_id_seq;
create sequence if not exists member_search_history_id_seq;
create sequence if not exists menu_id_seq;
create sequence if not exists menu_category_id_seq;
create sequence if not exists message_queue_trace_log_id_seq;
create sequence if not exists notification_id_seq;
create sequence if not exists promotion_id_seq;
create sequence if not exists promotion_asset_id_seq;
create sequence if not exists promotion_display_id_seq;
create sequence if not exists push_notification_target_id_seq;
create sequence if not exists restaurant_address_id_seq;
create sequence if not exists restaurant_food_category_id_seq;
create sequence if not exists restaurant_schedule_override_id_seq;
create sequence if not exists restaurant_weekly_schedule_id_seq;
create sequence if not exists review_id_seq;
create sequence if not exists review_keyword_id_seq;
create sequence if not exists subgroup_favorite_restaurant_id_seq;

create table if not exists ai_restaurant_comparison
(
    total_candidates   integer                     not null,
    validated_count    integer                     not null,
    analyzed_at        timestamp(6) with time zone,
    created_at         timestamp(6) with time zone not null,
    id                 bigint generated by default as identity
        primary key,
    restaurant_id      bigint                      not null
        unique,
    updated_at         timestamp(6) with time zone not null,
    status             varchar(32)                 not null
        constraint ai_restaurant_comparison_status_check
            check ((status)::text = ANY
        ((ARRAY ['ANALYZING'::character varying, 'COMPLETED'::character varying])::text[])),
    category_lift      jsonb                       not null,
    comparison_display jsonb                       not null
);

comment on table ai_restaurant_comparison is '음식점별 AI 비교 분석 스냅샷(1행)을 저장하는 테이블';

comment on column ai_restaurant_comparison.analyzed_at is '마지막 분석 완료 시점';

comment on column ai_restaurant_comparison.category_lift is '카테고리별 lift 비율. 예) service/price/food';

comment on column ai_restaurant_comparison.comparison_display is '비교 문장 목록';

alter table ai_restaurant_comparison
    owner to tasteam;

create table if not exists ai_restaurant_review_analysis
(
    negative_ratio     numeric(5, 4)               not null,
    positive_ratio     numeric(5, 4)               not null,
    analyzed_at        timestamp(6) with time zone,
    created_at         timestamp(6) with time zone not null,
    id                 bigint generated by default as identity
        primary key,
    restaurant_id      bigint                      not null
        unique,
    updated_at         timestamp(6) with time zone not null,
    status             varchar(32)                 not null
        constraint ai_restaurant_review_analysis_status_check
            check ((status)::text = ANY
        ((ARRAY ['ANALYZING'::character varying, 'COMPLETED'::character varying])::text[])),
    overall_summary    varchar(1000)               not null,
    category_summaries jsonb                       not null
);

comment on table ai_restaurant_review_analysis is '음식점별 AI 리뷰 분석 스냅샷(1행)을 저장하는 테이블';

comment on column ai_restaurant_review_analysis.negative_ratio is '부정 비율 (0.0000 ~ 1.0000)';

comment on column ai_restaurant_review_analysis.positive_ratio is '긍정 비율 (0.0000 ~ 1.0000)';

comment on column ai_restaurant_review_analysis.analyzed_at is '마지막 분석 완료 시점';

comment on column ai_restaurant_review_analysis.category_summaries is '카테고리별 요약. 예) service/price/food';

alter table ai_restaurant_review_analysis
    owner to tasteam;

create table if not exists announcement
(
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6) with time zone not null,
    title      varchar(200)                not null,
    content    text                        not null
);

alter table announcement
    owner to tasteam;

create table if not exists food_category
(
    id   bigint generated by default as identity
        primary key,
    name varchar(20) not null
);

comment on table food_category is '음식점 분류에 사용되는 음식 카테고리의 정보를 관리하는 테이블';

comment on column food_category.name is '빈 문자열 불가';

alter table food_category
    owner to tasteam;

alter sequence group_seq owner to tasteam;

create table if not exists "group"
(
    created_at     timestamp(6) with time zone not null,
    deleted_at     timestamp(6) with time zone,
    id             bigint                      not null
        primary key,
    updated_at     timestamp(6) with time zone not null,
    join_type      varchar(20)                 not null
        constraint group_join_type_check
            check ((join_type)::text = ANY
        ((ARRAY ['EMAIL'::character varying, 'PASSWORD'::character varying])::text[])),
    status         varchar(20)                 not null
        constraint group_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    type           varchar(20)                 not null
        constraint group_type_check
            check ((type)::text = ANY
                   ((ARRAY ['OFFICIAL'::character varying, 'UNOFFICIAL'::character varying])::text[])),
    email_domain   varchar(100),
    name           varchar(100)                not null,
    logo_image_url varchar(500),
    address        varchar(255)                not null,
    detail_address varchar(255),
    location       geometry(Point, 4326)
);

alter table "group"
    owner to tasteam;

alter sequence group_auth_code_seq owner to tasteam;

create table if not exists group_auth_code
(
    created_at  timestamp(6) with time zone not null,
    expires_at  timestamp(6) with time zone,
    group_id    bigint                      not null,
    id          bigint                      not null
        primary key,
    verified_at timestamp(6) with time zone,
    code        varchar(255)                not null,
    email       varchar(255)
);

alter table group_auth_code
    owner to tasteam;

create table if not exists image
(
    created_at  timestamp(6) with time zone not null,
    deleted_at  timestamp(6) with time zone,
    file_size   bigint                      not null,
    id          bigint                      not null
        primary key,
    updated_at  timestamp(6) with time zone not null,
    file_uuid   uuid                        not null
        unique,
    status      varchar(16)                 not null
        constraint image_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'DELETED'::character varying])::text[])),
    purpose     varchar(32)                 not null
        constraint image_purpose_check
            check ((purpose)::text = ANY
                   ((ARRAY ['REVIEW_IMAGE'::character varying, 'RESTAURANT_IMAGE'::character varying, 'MENU_IMAGE'::character varying, 'COMMON_ASSET'::character varying, 'PROFILE_IMAGE'::character varying, 'GROUP_IMAGE'::character varying])::text[])),
    file_type   varchar(64)                 not null,
    file_name   varchar(256)                not null,
    storage_key varchar(512)                not null
        unique
);

alter table image
    owner to tasteam;

create table if not exists domain_image
(
    sort_order  integer,
    created_at  timestamp(6) with time zone not null,
    domain_id   bigint                      not null,
    id          bigint                      not null
        primary key,
    image_id    bigint                      not null
        constraint fk7w4bvug5tgoyweoxbg0mqvng1
            references image,
    domain_type varchar(32)                 not null
        constraint domain_image_domain_type_check
            check ((domain_type)::text = ANY
        ((ARRAY ['REVIEW'::character varying, 'RESTAURANT'::character varying, 'PROMOTION'::character varying, 'GROUP'::character varying, 'MENU'::character varying, 'SUBGROUP'::character varying, 'MEMBER'::character varying])::text[])),
    constraint uq_domain_image_link
        unique (domain_type, domain_id, image_id)
);

alter table domain_image
    owner to tasteam;

create table if not exists image_optimization_job
(
    optimized_height integer,
    optimized_width  integer,
    original_height  integer,
    original_width   integer,
    created_at       timestamp(6) with time zone not null,
    id               bigint generated by default as identity
        primary key,
    image_id         bigint                      not null
        unique
        constraint fk3slrs4l11ltiwxg8v9hqkg75l
            references image,
    optimized_size   bigint,
    original_size    bigint,
    processed_at     timestamp(6) with time zone,
    status           varchar(32)                 not null
        constraint image_optimization_job_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'SKIPPED'::character varying])::text[])),
    error_message    text
);

alter table image_optimization_job
    owner to tasteam;

create table if not exists keyword
(
    id   bigint generated by default as identity
        primary key,
    type varchar(50)  not null
        constraint keyword_type_check
            check ((type)::text = ANY
        ((ARRAY ['VISIT_PURPOSE'::character varying, 'COMPANION_TYPE'::character varying, 'WAITING_EXPERIENCE'::character varying, 'POSITIVE_ASPECT'::character varying])::text[])),
    name varchar(200) not null,
    constraint uq_keyword_type_name
        unique (type, name)
);

comment on table keyword is '리뷰에 사용되는 키워드 사전';

alter table keyword
    owner to tasteam;

create table if not exists member
(
    agreed_privacy_at timestamp(6) with time zone,
    agreed_terms_at   timestamp(6) with time zone,
    created_at        timestamp(6) with time zone not null,
    deleted_at        timestamp(6) with time zone,
    id                bigint                      not null
        primary key,
    last_login_at     timestamp(6) with time zone,
    updated_at        timestamp(6) with time zone not null,
    role              varchar(20)                 not null
        constraint member_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    status            varchar(20)                 not null
        constraint member_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'BLOCKED'::character varying, 'WITHDRAWN'::character varying])::text[])),
    nickname          varchar(50)                 not null,
    introduction      varchar(500),
    profile_image_url varchar(500),
    email             varchar(255)
        unique
);

alter table member
    owner to tasteam;

alter sequence group_member_seq owner to tasteam;

create table if not exists group_member
(
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    group_id   bigint                      not null,
    id         bigint                      not null
        primary key,
    member_id  bigint                      not null
        constraint fkeamf7nngsg582uxwqgde8o28x
            references member,
    constraint uk_group_member_group_id_member_id
        unique (group_id, member_id)
);

comment on table group_member is '특정 그룹에 가입한 회원들의 가입, 탈퇴 상태를 관리하는 매핑 테이블';

alter table group_member
    owner to tasteam;

create table if not exists member_favorite_restaurant
(
    created_at    timestamp(6) with time zone not null,
    deleted_at    timestamp(6) with time zone,
    id            bigint generated by default as identity
        primary key,
    member_id     bigint                      not null,
    restaurant_id bigint                      not null,
    unique (member_id, restaurant_id)
);

alter table member_favorite_restaurant
    owner to tasteam;

create table if not exists member_notification_preference
(
    is_enabled        boolean                     not null,
    created_at        timestamp(6) with time zone not null,
    id                bigint generated by default as identity
        primary key,
    member_id         bigint                      not null,
    updated_at        timestamp(6) with time zone not null,
    channel           varchar(10)                 not null
        constraint member_notification_preference_channel_check
            check ((channel)::text = ANY
        ((ARRAY ['WEB'::character varying, 'PUSH'::character varying, 'EMAIL'::character varying, 'SMS'::character varying])::text[])),
    notification_type varchar(20)                 not null
        constraint member_notification_preference_notification_type_check
            check ((notification_type)::text = ANY
                   ((ARRAY ['CHAT'::character varying, 'SYSTEM'::character varying, 'NOTICE'::character varying])::text[])),
    constraint uq_preference
        unique (member_id, channel, notification_type)
);

alter table member_notification_preference
    owner to tasteam;

create table if not exists member_oauth_account
(
    created_at          timestamp(6) with time zone not null,
    id                  bigint                      not null
        primary key,
    member_id           bigint                      not null
        constraint fknhipml9fr0p71fnmhdgqtsfwo
            references member,
    provider            varchar(20)                 not null,
    provider_user_id    varchar(100)                not null,
    provider_user_email varchar(255),
    constraint uk_member_oauth_provider_user
        unique (provider, provider_user_id)
);

alter table member_oauth_account
    owner to tasteam;

create table if not exists member_search_history
(
    count      bigint                      not null,
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id         bigint generated by default as identity
        primary key,
    member_id  bigint                      not null,
    updated_at timestamp(6) with time zone not null,
    keyword    varchar(100)                not null
);

comment on table member_search_history is '회원 검색어 기록';

alter table member_search_history
    owner to tasteam;

create table if not exists message_queue_trace_log
(
    created_at        timestamp(6) with time zone not null,
    id                bigint generated by default as identity
        primary key,
    processing_millis bigint,
    provider          varchar(30)                 not null,
    stage             varchar(30)                 not null
        constraint message_queue_trace_log_stage_check
            check ((stage)::text = ANY
        ((ARRAY ['PUBLISH'::character varying, 'CONSUME_SUCCESS'::character varying, 'CONSUME_FAIL'::character varying])::text[])),
    consumer_group    varchar(100),
    message_id        varchar(100)                not null,
    topic             varchar(100)                not null,
    message_key       varchar(200),
    error_message     varchar(1000)
);

alter table message_queue_trace_log
    owner to tasteam;

create index if not exists idx_mq_trace_message_id
    on message_queue_trace_log (message_id asc, id desc);

create index if not exists idx_mq_trace_topic_stage
    on message_queue_trace_log (topic asc, stage asc, id desc);

create table if not exists notification
(
    created_at        timestamp(6) with time zone not null,
    id                bigint generated by default as identity
        primary key,
    member_id         bigint                      not null,
    read_at           timestamp(6) with time zone,
    notification_type varchar(20)                 not null
        constraint notification_notification_type_check
            check ((notification_type)::text = ANY
        ((ARRAY ['CHAT'::character varying, 'SYSTEM'::character varying, 'NOTICE'::character varying])::text[])),
    title             varchar(100)                not null,
    body              varchar(500)                not null,
    deep_link         varchar(500)
);

alter table notification
    owner to tasteam;

create index if not exists idx_notification_member_id
    on notification (member_id asc, id desc);

create index if not exists idx_notification_member_unread
    on notification (member_id, read_at, id);

create table if not exists promotion
(
    created_at         timestamp(6) with time zone not null,
    deleted_at         timestamp(6) with time zone,
    id                 bigint generated by default as identity
        primary key,
    promotion_end_at   timestamp(6) with time zone not null,
    promotion_start_at timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    publish_status     varchar(20)                 not null
        constraint promotion_publish_status_check
            check ((publish_status)::text = ANY
        ((ARRAY ['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[])),
    title              varchar(200)                not null,
    landing_url        varchar(500),
    content            text                        not null,
    constraint promotion_check
        check (promotion_start_at <= promotion_end_at)
);

alter table promotion
    owner to tasteam;

create table if not exists promotion_asset
(
    is_primary   boolean                     not null,
    sort_order   integer                     not null,
    created_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone,
    id           bigint generated by default as identity
        primary key,
    promotion_id bigint                      not null
        constraint fk3r4bv1gt6la1a66bekc9ygqib
            references promotion,
    updated_at   timestamp(6) with time zone not null,
    asset_type   varchar(30)                 not null
        constraint promotion_asset_asset_type_check
            check ((asset_type)::text = ANY
        ((ARRAY ['BANNER'::character varying, 'DETAIL'::character varying])::text[])),
    alt_text     varchar(200),
    image_url    varchar(500)                not null
);

alter table promotion_asset
    owner to tasteam;

create index if not exists idx_promotion_asset_type_order
    on promotion_asset (promotion_id, asset_type, sort_order);

create table if not exists promotion_display
(
    display_enabled  boolean                     not null,
    display_priority integer                     not null,
    created_at       timestamp(6) with time zone not null,
    deleted_at       timestamp(6) with time zone,
    display_end_at   timestamp(6) with time zone not null,
    display_start_at timestamp(6) with time zone not null,
    id               bigint generated by default as identity
        primary key,
    promotion_id     bigint                      not null
        constraint uk_promotion_display_promotion_id
            unique
        constraint fk97i22nhpk9kgovrjdqo01njr1
            references promotion,
    updated_at       timestamp(6) with time zone not null,
    display_channel  varchar(20)                 not null
        constraint promotion_display_display_channel_check
            check ((display_channel)::text = ANY
        ((ARRAY ['MAIN_BANNER'::character varying, 'PROMOTION_LIST'::character varying, 'BOTH'::character varying])::text[])),
    constraint promotion_display_check
        check (display_start_at <= display_end_at)
);

alter table promotion_display
    owner to tasteam;

create index if not exists idx_promotion_display_window
    on promotion_display (display_enabled, display_start_at, display_end_at);

create index if not exists idx_promotion_display_channel_priority
    on promotion_display (display_channel, display_priority);

create table if not exists push_notification_target
(
    created_at timestamp(6) with time zone not null,
    id         bigint generated by default as identity
        primary key,
    member_id  bigint                      not null,
    device_id  varchar(64),
    fcm_token  varchar(255)                not null
        constraint uq_fcm_token
            unique,
    constraint uq_member_device
        unique (member_id, device_id)
);

alter table push_notification_target
    owner to tasteam;

create index if not exists idx_push_target_member
    on push_notification_target (member_id, created_at);

create index if not exists idx_push_target_member_device
    on push_notification_target (member_id, device_id);

create table if not exists refresh_token
(
    created_at      timestamp(6) with time zone not null,
    expires_at      timestamp(6) with time zone not null,
    id              bigint                      not null
        primary key,
    member_id       bigint                      not null,
    revoked_at      timestamp(6) with time zone,
    rotated_at      timestamp(6) with time zone,
    token_family_id varchar(64)                 not null,
    token_hash      varchar(64)                 not null
        unique
);

alter table refresh_token
    owner to tasteam;

create index if not exists idx_refresh_token_member_id
    on refresh_token (member_id);

create index if not exists idx_refresh_token_family_id
    on refresh_token (token_family_id);

create index if not exists idx_refresh_token_expires_at
    on refresh_token (expires_at);

create table if not exists restaurant
(
    created_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone,
    id           bigint generated by default as identity
        primary key,
    updated_at   timestamp(6) with time zone not null,
    name         varchar(100)                not null,
    phone_number varchar(100),
    full_address varchar(255)                not null,
    location     geometry(Point, 4326)
);

comment on table restaurant is '음식점의 기본 정보를 저장하는 마스터 테이블';

comment on column restaurant.deleted_at is '소프트 삭제';

comment on column restaurant.name is '빈 문자열 불가';

comment on column restaurant.location is 'WGS84';

alter table restaurant
    owner to tasteam;

create table if not exists ai_restaurant_recommendation
(
    created_at    timestamp(6) with time zone not null,
    expires_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity
        primary key,
    restaurant_id bigint                      not null
        constraint fke5h2akcwff8wpnxab36uw72jt
            references restaurant,
    cache_key     varchar(120)                not null,
    reason        varchar(1000)               not null
);

comment on table ai_restaurant_recommendation is 'Vector 검색 추천 결과를 TTL 기반으로 저장하는 캐시 테이블';

comment on column ai_restaurant_recommendation.expires_at is '캐시 만료 시각 (기본 생성시각 + 1일)';

comment on column ai_restaurant_recommendation.cache_key is '추천 캐시 식별자 (예: memberId + query)';

comment on column ai_restaurant_recommendation.reason is '빈 문자열 불가';

alter table ai_restaurant_recommendation
    owner to tasteam;

create table if not exists menu_category
(
    display_order integer                     not null,
    created_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity
        primary key,
    restaurant_id bigint                      not null
        constraint fk4optm5vshejcitfiyt87e5lrl
            references restaurant,
    updated_at    timestamp(6) with time zone not null,
    name          varchar(50)                 not null
);

comment on table menu_category is '음식점의 메뉴 카테고리를 관리하는 테이블';

comment on column menu_category.display_order is '노출 순서 (0 이상 정수)';

comment on column menu_category.name is '카테고리 이름 (예: 메인, 음료)';

alter table menu_category
    owner to tasteam;

create table if not exists menu
(
    display_order  integer                     not null,
    is_recommended boolean                     not null,
    price          integer                     not null,
    category_id    bigint
        constraint fkawj601wd3bdmqnyovuqbhqcgg
            references menu_category,
    created_at     timestamp(6) with time zone not null,
    id             bigint generated by default as identity
        primary key,
    updated_at     timestamp(6) with time zone not null,
    name           varchar(100)                not null,
    description    varchar(500),
    image_url      varchar(500)
);

comment on table menu is '음식점의 메뉴 항목을 관리하는 테이블';

comment on column menu.display_order is '노출 순서 (0 이상 정수)';

comment on column menu.is_recommended is '추천 메뉴 여부';

comment on column menu.price is '메뉴 가격 (0 이상 정수)';

comment on column menu.name is '메뉴 이름';

comment on column menu.description is '메뉴 설명';

comment on column menu.image_url is '메뉴 이미지 URL';

alter table menu
    owner to tasteam;

create index if not exists idx_menu_category_order
    on menu (category_id, display_order);

create index if not exists idx_menu_category_restaurant_order
    on menu_category (restaurant_id, display_order);

create table if not exists restaurant_address
(
    created_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity
        primary key,
    restaurant_id bigint                      not null
        unique
        constraint fkfqnrtvk7yn887qcwy8qmyqylb
            references restaurant,
    updated_at    timestamp(6) with time zone not null,
    postal_code   varchar(16),
    sido          varchar(20),
    eupmyeondong  varchar(30),
    sigungu       varchar(30)
);

comment on table restaurant_address is '음식점의 주소 정보를 관리하는 테이블';

comment on column restaurant_address.postal_code is '우편번호';

comment on column restaurant_address.sido is '시/도';

comment on column restaurant_address.eupmyeondong is '읍/면/동';

comment on column restaurant_address.sigungu is '시/군/구';

alter table restaurant_address
    owner to tasteam;

create table if not exists restaurant_food_category
(
    food_category_id bigint not null
        constraint fk6e8lbtb2tptceeysa33epwc4d
            references food_category,
    id               bigint generated by default as identity
        primary key,
    restaurant_id    bigint not null
        constraint fk9wk7qg0x1du4bi3yyu0ptvnkk
            references restaurant,
    unique (restaurant_id, food_category_id)
);

comment on table restaurant_food_category is '음식점과 음식 카테고리 간의 매핑 테이블';

alter table restaurant_food_category
    owner to tasteam;

create table if not exists restaurant_schedule_override
(
    close_time    time(6),
    date          date                        not null,
    is_closed     boolean                     not null,
    open_time     time(6),
    created_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity
        primary key,
    restaurant_id bigint                      not null
        constraint fkl0cjk521603ki83secks6ttyg
            references restaurant,
    updated_at    timestamp(6) with time zone not null,
    reason        varchar(255),
    constraint uk_restaurant_schedule_override_restaurant_date
        unique (restaurant_id, date)
);

comment on table restaurant_schedule_override is '음식점의 특정 날짜 예외 영업 시간을 관리하는 테이블';

comment on column restaurant_schedule_override.close_time is '마감 시간 (HH:mm)';

comment on column restaurant_schedule_override.date is '예외 적용 날짜';

comment on column restaurant_schedule_override.is_closed is '휴무 여부';

comment on column restaurant_schedule_override.open_time is '오픈 시간 (HH:mm)';

comment on column restaurant_schedule_override.reason is '예외 사유';

alter table restaurant_schedule_override
    owner to tasteam;

create table if not exists restaurant_weekly_schedule
(
    close_time     time(6),
    day_of_week    integer                     not null,
    effective_from date,
    effective_to   date,
    is_closed      boolean                     not null,
    open_time      time(6),
    created_at     timestamp(6) with time zone not null,
    id             bigint generated by default as identity
        primary key,
    restaurant_id  bigint                      not null
        constraint fk2oe0e2lt9ugxnxwvk5qsochbd
            references restaurant,
    updated_at     timestamp(6) with time zone not null
);

comment on table restaurant_weekly_schedule is '음식점의 요일별 정기 영업 시간을 관리하는 테이블';

comment on column restaurant_weekly_schedule.close_time is '마감 시간 (HH:mm)';

comment on column restaurant_weekly_schedule.day_of_week is '요일 (1=월요일 ~ 7=일요일)';

comment on column restaurant_weekly_schedule.effective_from is '정책 유효 시작일';

comment on column restaurant_weekly_schedule.effective_to is '정책 유효 종료일';

comment on column restaurant_weekly_schedule.is_closed is '휴무일 여부';

comment on column restaurant_weekly_schedule.open_time is '오픈 시간 (HH:mm)';

alter table restaurant_weekly_schedule
    owner to tasteam;

create index if not exists idx_restaurant_weekly_schedule_lookup
    on restaurant_weekly_schedule (restaurant_id, day_of_week, effective_from, effective_to);

create table if not exists review
(
    is_recommended boolean                     not null,
    created_at     timestamp(6) with time zone not null,
    deleted_at     timestamp(6) with time zone,
    group_id       bigint                      not null,
    id             bigint generated by default as identity
        primary key,
    member_id      bigint                      not null
        constraint fkk0ccx5i4ci2wd70vegug074w1
            references member,
    restaurant_id  bigint                      not null
        constraint fk70ry7cuti298yxet366rynxch
            references restaurant,
    subgroup_id    bigint,
    updated_at     timestamp(6) with time zone not null,
    content        varchar(1000)
);

comment on table review is '그룹/하위 그룹 단위로 작성되는 음식점 리뷰';

alter table review
    owner to tasteam;

create table if not exists review_keyword
(
    id         bigint generated by default as identity
        primary key,
    keyword_id bigint not null
        constraint fkq57jeojppunwgw4y9w8ruon9g
            references keyword,
    review_id  bigint not null
        constraint fk2e08kygbei0sj85rys25wij64
            references review,
    constraint uq_review_keyword
        unique (review_id, keyword_id)
);

comment on table review_keyword is '리뷰-키워드 매핑';

alter table review_keyword
    owner to tasteam;

create table if not exists subgroup
(
    member_count      integer                     not null,
    created_at        timestamp(6) with time zone not null,
    deleted_at        timestamp(6) with time zone,
    group_id          bigint                      not null
        constraint fkpor7f0w6094adpkxvcbkucnkp
            references "group",
    id                bigint                      not null
        primary key,
    updated_at        timestamp(6) with time zone not null,
    join_type         varchar(20)                 not null
        constraint subgroup_join_type_check
            check ((join_type)::text = ANY
        ((ARRAY ['OPEN'::character varying, 'PASSWORD'::character varying])::text[])),
    status            varchar(20)                 not null
        constraint subgroup_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    name              varchar(100)                not null,
    description       varchar(500),
    profile_image_url varchar(500),
    join_password     varchar(255)
);

alter table subgroup
    owner to tasteam;

create table if not exists subgroup_favorite_restaurant
(
    created_at    timestamp(6) with time zone not null,
    deleted_at    timestamp(6) with time zone,
    id            bigint generated by default as identity
        primary key,
    member_id     bigint                      not null,
    restaurant_id bigint                      not null,
    subgroup_id   bigint                      not null
);

alter table subgroup_favorite_restaurant
    owner to tasteam;

create table if not exists subgroup_member
(
    created_at  timestamp(6) with time zone not null,
    deleted_at  timestamp(6) with time zone,
    id          bigint                      not null
        primary key,
    member_id   bigint                      not null
        constraint fkfpu33hwtjqp93p9xs7m1i2sbp
            references member,
    subgroup_id bigint                      not null,
    constraint uk_subgroup_member_subgroup_id_member_id
        unique (subgroup_id, member_id)
);

comment on table subgroup_member is '하위그룹에 가입한 회원들의 가입, 탈퇴 상태를 관리하는 매핑 테이블';

alter table subgroup_member
    owner to tasteam;
