-- subgroup.id가 subgroup_seq(START 1, INCREMENT 50)를 pooled 옵티마이저로 사용하면
-- 첫 번째 풀의 ID 범위가 [-48, 1]이 되어 음수 ID가 발생할 수 있다.
-- GenerationType.IDENTITY로 전환하여 항상 양수 ID를 보장한다.
DO $$
DECLARE
    next_id bigint;
    seq_name text;
BEGIN
    SELECT GREATEST(COALESCE(MAX(id), 0) + 1, 1) INTO next_id FROM subgroup;
    ALTER TABLE subgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);
    seq_name := pg_get_serial_sequence('subgroup', 'id');
    PERFORM setval(seq_name, next_id, false);
END $$;

DROP SEQUENCE IF EXISTS subgroup_seq;
