global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: postgres
    scrape_interval: 15s
    static_configs:
      - targets:
          - postgres-exporter:9187
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: backend

  - job_name: redis
    scrape_interval: 15s
    static_configs:
      - targets:
          - redis-exporter:9121
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: backend

  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets:
          - node-exporter:9100
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: backend

  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - cadvisor:8080
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: backend

  - job_name: tasteam-alloy
    scrape_interval: 15s
    static_configs:
      - targets:
          - alloy:12345
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: monitoring

  - job_name: kafka-broker-jmx
    scrape_interval: 15s
    static_configs:
      - targets:
          - kafka-jmx-exporter:7071
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: kafka

  - job_name: kafka-connect-jmx
    scrape_interval: 15s
    static_configs:
      - targets:
          - connect-jmx-exporter:7072
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: kafka

  - job_name: kafka-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - kafka-exporter:9308
    relabel_configs:
      - target_label: environment
        replacement: local
      - target_label: instance
        replacement: tasteam-local
      - target_label: role
        replacement: kafka
