package com.tasteam.batch.dummy.repository;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import lombok.RequiredArgsConstructor;

@Repository
@RequiredArgsConstructor
public class DummyDataJdbcRepository {

	private static final int CHUNK = 500;

	private final JdbcTemplate jdbcTemplate;

	// ── INSERT methods ────────────────────────────────────────────────────────

	/**
	 * member 테이블에 더미 멤버를 배치 삽입한다.
	 * ID는 PostgreSQL sequence(member_seq)에서 직접 소비된다.
	 */
	public List<Long> insertMembers(List<String> emails, List<String> nicknames) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(emails.size());
		int n = emails.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO member (id, email, nickname, status, role, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('member_seq'),?,?,'ACTIVE','USER',?,?)");
				p.add(emails.get(start + i));
				p.add(nicknames.get(start + i));
				p.add(now);
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * restaurant 테이블에 더미 음식점을 배치 삽입한다.
	 * ID는 IDENTITY(generated by default)로 자동 생성된다.
	 */
	public List<Long> insertRestaurants(List<String> names, List<String> addresses) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(names.size());
		int n = names.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO restaurant (name, full_address, vector_epoch, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,0,?,?)");
				p.add(names.get(start + i));
				p.add(addresses.get(start + i));
				p.add(now);
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * "group" 테이블에 더미 그룹을 배치 삽입한다.
	 * ID는 PostgreSQL sequence(group_seq)에서 직접 소비된다.
	 */
	public List<Long> insertGroups(List<String> names, List<String> addresses) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(names.size());
		int n = names.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO \"group\" (id, name, type, address, join_type, status, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('group_seq'),?,'UNOFFICIAL',?,'PASSWORD','ACTIVE',?,?)");
				p.add(names.get(start + i));
				p.add(addresses.get(start + i));
				p.add(now);
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * group_member 테이블에 배치 삽입한다. (그룹-멤버 매핑)
	 * pairs: [groupId, memberId]
	 */
	public void insertGroupMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO group_member (id, group_id, member_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 3);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('group_member_seq'),?,?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * subgroup 테이블에 더미 하위그룹을 배치 삽입한다.
	 * ID는 PostgreSQL sequence(subgroup_seq)에서 직접 소비된다.
	 */
	public List<Long> insertSubgroups(List<Long> groupIds, List<String> names) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(groupIds.size());
		int n = groupIds.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO subgroup (id, group_id, name, join_type, status, member_count, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('subgroup_seq'),?,?,'OPEN','ACTIVE',0,?,?)");
				p.add(groupIds.get(start + i));
				p.add(names.get(start + i));
				p.add(now);
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * chat_room 테이블에 subgroup과 1:1로 채팅방을 배치 삽입한다.
	 * 반환 리스트는 입력 subgroupIds와 동일한 순서다.
	 */
	public List<Long> insertChatRooms(List<Long> subgroupIds) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(subgroupIds.size());
		int n = subgroupIds.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_room (subgroup_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 2);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?)");
				p.add(subgroupIds.get(start + i));
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * subgroup_member 테이블에 배치 삽입한다. (하위그룹-멤버 매핑)
	 * pairs: [subgroupId, memberId]
	 */
	public void insertSubgroupMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO subgroup_member (id, subgroup_id, member_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 3);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('subgroup_member_seq'),?,?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * chat_room_member 테이블에 배치 삽입한다.
	 * pairs: [chatRoomId, memberId]
	 */
	public void insertChatRoomMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_room_member (member_id, chat_room_id, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,?)");
				p.add(pairs.get(start + i)[1]);
				p.add(pairs.get(start + i)[0]);
				p.add(now);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * subgroup.member_count를 하위그룹별 실제 삽입 수로 일괄 업데이트한다.
	 */
	public void updateSubgroupMemberCounts(Map<Long, Integer> counts) {
		List<Object[]> batchArgs = new ArrayList<>(counts.size());
		for (Map.Entry<Long, Integer> e : counts.entrySet()) {
			batchArgs.add(new Object[] {e.getValue(), e.getKey()});
		}
		jdbcTemplate.batchUpdate(
			"UPDATE subgroup SET member_count = ? WHERE id = ?",
			batchArgs);
	}

	/**
	 * review 테이블에 더미 리뷰를 배치 삽입한다.
	 * entries: [memberId, restaurantId, groupId, isRecommended(1=true,0=false)]
	 */
	public List<Long> insertReviews(List<long[]> entries, List<String> contents) {
		Timestamp now = ts();
		List<Long> ids = new ArrayList<>(entries.size());
		int n = entries.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO review (member_id, restaurant_id, group_id, is_recommended, content, created_at, updated_at)"
					+ " VALUES ");
			List<Object> p = new ArrayList<>(size * 5);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,?,?,?,?)");
				long[] e = entries.get(start + i);
				p.add(e[0]);
				p.add(e[1]);
				p.add(e[2]);
				p.add(e[3] == 1);
				p.add(contents.get(start + i));
				p.add(now);
				p.add(now);
			}
			sql.append(" RETURNING id");
			ids.addAll(jdbcTemplate.query(sql.toString(), (rs, row) -> rs.getLong("id"), p.toArray()));
		}
		return ids;
	}

	/**
	 * 현재 DB에 존재하는 키워드 ID 목록을 조회한다.
	 */
	public List<Long> queryKeywordIds() {
		return jdbcTemplate.queryForList("SELECT id FROM keyword ORDER BY id", Long.class);
	}

	/**
	 * review_keyword 테이블에 배치 삽입한다. (리뷰-키워드 매핑)
	 * pairs: [reviewId, keywordId]
	 */
	public void insertReviewKeywords(List<long[]> pairs) {
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO review_keyword (review_id, keyword_id) VALUES ");
			List<Object> p = new ArrayList<>(size * 2);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * chat_message 테이블에 더미 채팅 메시지를 배치 삽입한다.
	 * entries: [chatRoomId, memberId]
	 */
	public int insertChatMessages(List<long[]> entries, List<String> contents) {
		Timestamp now = ts();
		int n = entries.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_message (chat_room_id, member_id, type, content, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 5);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,'TEXT',?,?)");
				long[] e = entries.get(start + i);
				p.add(e[0]);
				p.add(e[1]);
				p.add(contents.get(start + i));
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return n;
	}

	// ── DELETE ────────────────────────────────────────────────────────────────

	/**
	 * 더미 데이터를 외래키 제약 순서에 맞춰 전부 삭제한다.
	 * 더미 멤버는 email LIKE '%@dummy.tasteam.kr', 더미 그룹은 name LIKE '더미그룹-%',
	 * 더미 음식점은 name LIKE '더미식당-%' 로 식별한다.
	 */
	public void deleteDummyData() {
		// 1. 더미 멤버가 작성한 리뷰의 키워드 삭제
		jdbcTemplate.update("""
			DELETE FROM review_keyword
			WHERE review_id IN (
			    SELECT id FROM review
			    WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			)
			""");

		// 2. 더미 멤버가 작성한 리뷰 삭제
		jdbcTemplate.update("""
			DELETE FROM review
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 3. 더미 멤버의 그룹 가입 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM group_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 4. 더미 멤버의 하위그룹 가입 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM subgroup_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 5. 더미 멤버의 채팅방 멤버 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_room_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 6. 더미 그룹 산하 채팅방의 메시지 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_message
			WHERE chat_room_id IN (
			    SELECT cr.id FROM chat_room cr
			    JOIN subgroup sg ON cr.subgroup_id = sg.id
			    WHERE sg.group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 7. 더미 그룹 산하 채팅방의 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM chat_room_member
			WHERE chat_room_id IN (
			    SELECT cr.id FROM chat_room cr
			    JOIN subgroup sg ON cr.subgroup_id = sg.id
			    WHERE sg.group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 8. 더미 그룹 산하 채팅방 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_room
			WHERE subgroup_id IN (
			    SELECT id FROM subgroup
			    WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 9. 더미 그룹 산하 하위그룹 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM subgroup_member
			WHERE subgroup_id IN (
			    SELECT id FROM subgroup
			    WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 10. 더미 그룹의 하위그룹 삭제
		jdbcTemplate.update("""
			DELETE FROM subgroup
			WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			""");

		// 11. 더미 그룹의 그룹 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM group_member
			WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			""");

		// 12. 더미 그룹 삭제
		jdbcTemplate.update("DELETE FROM \"group\" WHERE name LIKE '더미그룹-%'");

		// 13. 더미 음식점에 달린 리뷰 키워드 삭제
		jdbcTemplate.update("""
			DELETE FROM review_keyword
			WHERE review_id IN (
			    SELECT id FROM review
			    WHERE restaurant_id IN (SELECT id FROM restaurant WHERE name LIKE '더미식당-%')
			)
			""");

		// 14. 더미 음식점 리뷰 삭제
		jdbcTemplate.update("""
			DELETE FROM review
			WHERE restaurant_id IN (SELECT id FROM restaurant WHERE name LIKE '더미식당-%')
			""");

		// 15. 더미 음식점 삭제
		jdbcTemplate.update("DELETE FROM restaurant WHERE name LIKE '더미식당-%'");

		// 16. 더미 멤버 삭제
		jdbcTemplate.update("DELETE FROM member WHERE email LIKE '%@dummy.tasteam.kr'");
	}

	// ── COUNT ─────────────────────────────────────────────────────────────────

	public long countMembers() {
		return query("SELECT COUNT(*) FROM member WHERE deleted_at IS NULL");
	}

	public long countRestaurants() {
		return query("SELECT COUNT(*) FROM restaurant WHERE deleted_at IS NULL");
	}

	public long countGroups() {
		return query("SELECT COUNT(*) FROM \"group\" WHERE deleted_at IS NULL");
	}

	public long countSubgroups() {
		return query("SELECT COUNT(*) FROM subgroup WHERE deleted_at IS NULL");
	}

	public long countReviews() {
		return query("SELECT COUNT(*) FROM review WHERE deleted_at IS NULL");
	}

	public long countChatMessages() {
		return query("SELECT COUNT(*) FROM chat_message WHERE deleted_at IS NULL");
	}

	// ── helpers ───────────────────────────────────────────────────────────────

	private Timestamp ts() {
		return Timestamp.from(Instant.now());
	}

	private long query(String sql) {
		Long result = jdbcTemplate.queryForObject(sql, Long.class);
		return result != null ? result : 0L;
	}
}
