package com.tasteam.batch.dummy.repository;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import lombok.RequiredArgsConstructor;

@Repository
@RequiredArgsConstructor
public class DummyDataJdbcRepository {

	/**
	 * 한 번의 multi-row INSERT에 담을 최대 행 수.
	 * 최대 컬럼 수(7) × 5,000 = 35,000으로 PostgreSQL 파라미터 한도(65,535) 이내.
	 * DummyDataSeedService.SERVICE_CHUNK_SIZE(5,000)와 일치시켜 서비스→레포 사이의 재분할 제거.
	 */
	private static final int CHUNK = 5_000;

	private final JdbcTemplate jdbcTemplate;

	// ── INSERT methods ────────────────────────────────────────────────────────

	/**
	 * member 테이블에 더미 멤버를 배치 삽입한다.
	 * ID는 PostgreSQL sequence(member_seq)에서 직접 소비된다.
	 */
	@Transactional
	public List<Long> insertMembers(List<String> emails, List<String> nicknames) {
		Timestamp now = ts();
		int n = emails.size();
		List<Long> allIds = preallocateIds("member_seq", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO member (id, email, nickname, status, role, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 7);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,'ACTIVE','USER',?,?)");
				p.add(allIds.get(start + i));
				p.add(emails.get(start + i));
				p.add(nicknames.get(start + i));
				p.add(now);
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * restaurant 테이블에 더미 음식점을 배치 삽입한다.
	 * ID는 IDENTITY(generated by default)로 자동 생성된다.
	 */
	@Transactional
	public List<Long> insertRestaurants(List<String> names, List<String> addresses) {
		Timestamp now = ts();
		int n = names.size();
		List<Long> allIds = preallocateIdentityIds("restaurant", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO restaurant (id, name, full_address, vector_epoch, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 6);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,0,?,?)");
				p.add(allIds.get(start + i));
				p.add(names.get(start + i));
				p.add(addresses.get(start + i));
				p.add(now);
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * "group" 테이블에 더미 그룹을 배치 삽입한다.
	 * ID는 PostgreSQL sequence(group_seq)에서 직접 소비된다.
	 */
	@Transactional
	public List<Long> insertGroups(List<String> names, List<String> addresses) {
		Timestamp now = ts();
		int n = names.size();
		List<Long> allIds = preallocateIds("group_seq", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO \"group\" (id, name, type, address, join_type, status, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 8);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,'UNOFFICIAL',?,'PASSWORD','ACTIVE',?,?)");
				p.add(allIds.get(start + i));
				p.add(names.get(start + i));
				p.add(addresses.get(start + i));
				p.add(now);
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * group_member 테이블에 배치 삽입한다. (그룹-멤버 매핑)
	 * pairs: [groupId, memberId]
	 */
	@Transactional
	public void insertGroupMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO group_member (id, group_id, member_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('group_member_seq'),?,?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * subgroup 테이블에 더미 하위그룹을 배치 삽입한다.
	 * ID는 PostgreSQL sequence(subgroup_seq)에서 직접 소비된다.
	 */
	@Transactional
	public List<Long> insertSubgroups(List<Long> groupIds, List<String> names) {
		Timestamp now = ts();
		int n = groupIds.size();
		List<Long> allIds = preallocateIds("subgroup_seq", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO subgroup (id, group_id, name, join_type, status, member_count, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 8);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,'OPEN','ACTIVE',0,?,?)");
				p.add(allIds.get(start + i));
				p.add(groupIds.get(start + i));
				p.add(names.get(start + i));
				p.add(now);
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * chat_room 테이블에 subgroup과 1:1로 채팅방을 배치 삽입한다.
	 * 반환 리스트는 입력 subgroupIds와 동일한 순서다.
	 */
	@Transactional
	public List<Long> insertChatRooms(List<Long> subgroupIds) {
		Timestamp now = ts();
		int n = subgroupIds.size();
		List<Long> allIds = preallocateIds("chat_room_id_seq", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_room (id, subgroup_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 3);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?)");
				p.add(allIds.get(start + i));
				p.add(subgroupIds.get(start + i));
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * subgroup_member 테이블에 배치 삽입한다. (하위그룹-멤버 매핑)
	 * pairs: [subgroupId, memberId]
	 */
	@Transactional
	public void insertSubgroupMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO subgroup_member (id, subgroup_id, member_id, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(nextval('subgroup_member_seq'),?,?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * chat_room_member 테이블에 배치 삽입한다.
	 * pairs: [chatRoomId, memberId]
	 */
	@Transactional
	public void insertChatRoomMembers(List<long[]> pairs) {
		Timestamp now = ts();
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_room_member (member_id, chat_room_id, created_at, updated_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 4);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,?)");
				p.add(pairs.get(start + i)[1]);
				p.add(pairs.get(start + i)[0]);
				p.add(now);
				p.add(now);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * subgroup.member_count를 단일 CASE WHEN UPDATE로 일괄 갱신한다.
	 * N번 UPDATE 대신 1번 UPDATE로 처리.
	 */
	@Transactional
	public void updateSubgroupMemberCounts(Map<Long, Integer> counts) {
		if (counts.isEmpty()) {
			return;
		}

		int n = counts.size();
		// 파라미터: WHEN ? THEN ? 가 n개, IN (?) 가 n개 → 총 3n개
		List<Object> params = new ArrayList<>(n * 3);
		List<Long> ids = new ArrayList<>(n);

		StringBuilder sql = new StringBuilder("UPDATE subgroup SET member_count = CASE id ");
		for (Map.Entry<Long, Integer> e : counts.entrySet()) {
			sql.append("WHEN ? THEN ? ");
			params.add(e.getKey());
			params.add(e.getValue());
			ids.add(e.getKey());
		}
		sql.append("ELSE member_count END WHERE id IN (");
		for (int i = 0; i < ids.size(); i++) {
			if (i > 0)
				sql.append(',');
			sql.append('?');
			params.add(ids.get(i));
		}
		sql.append(')');

		jdbcTemplate.update(sql.toString(), params.toArray());
	}

	/**
	 * review 테이블에 더미 리뷰를 배치 삽입한다.
	 * entries: [memberId, restaurantId, groupId, isRecommended(1=true,0=false)]
	 */
	@Transactional
	public List<Long> insertReviews(List<long[]> entries, List<String> contents) {
		Timestamp now = ts();
		int n = entries.size();
		List<Long> allIds = preallocateIdentityIds("review", n);

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO review (id, member_id, restaurant_id, group_id, is_recommended, content, created_at, updated_at)"
					+ " VALUES ");
			List<Object> p = new ArrayList<>(size * 8);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,?,?,?,?,?,?)");
				long[] e = entries.get(start + i);
				p.add(allIds.get(start + i));
				p.add(e[0]);
				p.add(e[1]);
				p.add(e[2]);
				p.add(e[3] == 1);
				p.add(contents.get(start + i));
				p.add(now);
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return allIds;
	}

	/**
	 * 현재 DB에 존재하는 키워드 ID 목록을 조회한다.
	 */
	public List<Long> queryKeywordIds() {
		return jdbcTemplate.queryForList("SELECT id FROM keyword ORDER BY id", Long.class);
	}

	/**
	 * review_keyword 테이블에 배치 삽입한다. (리뷰-키워드 매핑)
	 * pairs: [reviewId, keywordId]
	 */
	@Transactional
	public void insertReviewKeywords(List<long[]> pairs) {
		int n = pairs.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO review_keyword (review_id, keyword_id) VALUES ");
			List<Object> p = new ArrayList<>(size * 2);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?)");
				p.add(pairs.get(start + i)[0]);
				p.add(pairs.get(start + i)[1]);
			}
			sql.append(" ON CONFLICT DO NOTHING");
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
	}

	/**
	 * chat_message 테이블에 더미 채팅 메시지를 배치 삽입한다.
	 * entries: [chatRoomId, memberId]
	 */
	@Transactional
	public int insertChatMessages(List<long[]> entries, List<String> contents) {
		Timestamp now = ts();
		int n = entries.size();

		for (int start = 0; start < n; start += CHUNK) {
			int end = Math.min(start + CHUNK, n);
			int size = end - start;

			StringBuilder sql = new StringBuilder(
				"INSERT INTO chat_message (chat_room_id, member_id, type, content, created_at) VALUES ");
			List<Object> p = new ArrayList<>(size * 5);

			for (int i = 0; i < size; i++) {
				if (i > 0)
					sql.append(',');
				sql.append("(?,?,'TEXT',?,?)");
				long[] e = entries.get(start + i);
				p.add(e[0]);
				p.add(e[1]);
				p.add(contents.get(start + i));
				p.add(now);
			}
			jdbcTemplate.update(sql.toString(), p.toArray());
		}
		return n;
	}

	private static final String[] NOTIFICATION_TYPES = {
		"REVIEW_COMMENT", "REVIEW_LIKE", "GROUP_JOIN", "ANNOUNCEMENT", "PROMOTION"
	};

	/**
	 * notification 테이블에 더미 알림을 단일 배치 삽입한다. (서비스 청크 단위로 호출)
	 * startSeq ~ startSeq+batchSize-1 범위의 seq를 사용해 event_id를 생성한다.
	 * ON CONFLICT (event_id) DO NOTHING으로 중복 삽입 방지.
	 */
	@Transactional
	public long insertNotificationBatch(List<Long> memberIds, int startSeq, int batchSize) {
		Timestamp now = ts();
		int memberSize = memberIds.size();

		StringBuilder sql = new StringBuilder(
			"INSERT INTO notification (member_id, notification_type, title, body, event_id, created_at)"
				+ " VALUES ");
		List<Object> p = new ArrayList<>(batchSize * 6);

		for (int i = 0; i < batchSize; i++) {
			if (i > 0)
				sql.append(',');
			int seq = startSeq + i;
			long memberId = memberIds.get(seq % memberSize);
			String type = NOTIFICATION_TYPES[seq % NOTIFICATION_TYPES.length];
			String eventId = "dummy-" + seq + "-" + UUID.randomUUID().toString().replace("-", "").substring(0, 8);
			sql.append("(?,?,?,?,?,?)");
			p.add(memberId);
			p.add(type);
			p.add("더미 알림 제목 " + (seq + 1));
			p.add("더미 알림 내용입니다. " + (seq + 1));
			p.add(eventId);
			p.add(now);
		}
		sql.append(" ON CONFLICT (event_id) DO NOTHING");
		return jdbcTemplate.update(sql.toString(), p.toArray());
	}

	/**
	 * member_favorite_restaurant 테이블에 더미 즐겨찾기를 단일 배치 삽입한다. (서비스 청크 단위로 호출)
	 * seq를 (memberIdx, restaurantIdx) 2차원 좌표로 전개해 (member_id, restaurant_id) 중복을 최소화한다.
	 * 최대 고유 행 수 = memberCount × restaurantCount.
	 * (member_id, restaurant_id) 중복 방지: ON CONFLICT DO NOTHING.
	 */
	@Transactional
	public long insertFavoriteBatch(List<Long> memberIds, List<Long> restaurantIds, int startSeq, int batchSize) {
		Timestamp now = ts();
		int memberSize = memberIds.size();
		int restaurantSize = restaurantIds.size();

		StringBuilder sql = new StringBuilder(
			"INSERT INTO member_favorite_restaurant (member_id, restaurant_id, created_at) VALUES ");
		List<Object> p = new ArrayList<>(batchSize * 3);

		for (int i = 0; i < batchSize; i++) {
			if (i > 0)
				sql.append(',');
			int seq = startSeq + i;
			// seq를 2차원으로 전개: memberIdx × restaurantIdx 매트릭스 순회
			int memberIdx = seq % memberSize;
			int restaurantIdx = (seq / memberSize) % restaurantSize;
			sql.append("(?,?,?)");
			p.add(memberIds.get(memberIdx));
			p.add(restaurantIds.get(restaurantIdx));
			p.add(now);
		}
		sql.append(" ON CONFLICT DO NOTHING");
		return jdbcTemplate.update(sql.toString(), p.toArray());
	}

	// ── DELETE ────────────────────────────────────────────────────────────────

	/**
	 * 더미 데이터를 외래키 제약 순서에 맞춰 전부 삭제한다.
	 */
	public void deleteDummyData() {
		// 0-a. 더미 멤버의 즐겨찾기 삭제
		jdbcTemplate.update("""
			DELETE FROM member_favorite_restaurant
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 0-b. 더미 멤버의 알림 삭제
		jdbcTemplate.update("""
			DELETE FROM notification
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 1. 더미 멤버가 작성한 리뷰의 키워드 삭제
		jdbcTemplate.update("""
			DELETE FROM review_keyword
			WHERE review_id IN (
			    SELECT id FROM review
			    WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			)
			""");

		// 2. 더미 멤버가 작성한 리뷰 삭제
		jdbcTemplate.update("""
			DELETE FROM review
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 3. 더미 멤버의 그룹 가입 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM group_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 4. 더미 멤버의 하위그룹 가입 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM subgroup_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 5. 더미 멤버의 채팅방 멤버 내역 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_room_member
			WHERE member_id IN (SELECT id FROM member WHERE email LIKE '%@dummy.tasteam.kr')
			""");

		// 6. 더미 그룹 산하 채팅방의 메시지 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_message
			WHERE chat_room_id IN (
			    SELECT cr.id FROM chat_room cr
			    JOIN subgroup sg ON cr.subgroup_id = sg.id
			    WHERE sg.group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 7. 더미 그룹 산하 채팅방의 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM chat_room_member
			WHERE chat_room_id IN (
			    SELECT cr.id FROM chat_room cr
			    JOIN subgroup sg ON cr.subgroup_id = sg.id
			    WHERE sg.group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 8. 더미 그룹 산하 채팅방 삭제
		jdbcTemplate.update("""
			DELETE FROM chat_room
			WHERE subgroup_id IN (
			    SELECT id FROM subgroup
			    WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 9. 더미 그룹 산하 하위그룹 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM subgroup_member
			WHERE subgroup_id IN (
			    SELECT id FROM subgroup
			    WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			)
			""");

		// 10. 더미 그룹의 하위그룹 삭제
		jdbcTemplate.update("""
			DELETE FROM subgroup
			WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			""");

		// 11. 더미 그룹의 그룹 멤버 내역 삭제 (위에서 남은 것 정리)
		jdbcTemplate.update("""
			DELETE FROM group_member
			WHERE group_id IN (SELECT id FROM "group" WHERE name LIKE '더미그룹-%')
			""");

		// 12. 더미 그룹 삭제
		jdbcTemplate.update("DELETE FROM \"group\" WHERE name LIKE '더미그룹-%'");

		// 13. 더미 음식점에 달린 리뷰 키워드 삭제
		jdbcTemplate.update("""
			DELETE FROM review_keyword
			WHERE review_id IN (
			    SELECT id FROM review
			    WHERE restaurant_id IN (SELECT id FROM restaurant WHERE name LIKE '더미식당-%')
			)
			""");

		// 14. 더미 음식점 리뷰 삭제
		jdbcTemplate.update("""
			DELETE FROM review
			WHERE restaurant_id IN (SELECT id FROM restaurant WHERE name LIKE '더미식당-%')
			""");

		// 15. 더미 음식점 삭제
		jdbcTemplate.update("DELETE FROM restaurant WHERE name LIKE '더미식당-%'");

		// 16. 더미 멤버 삭제
		jdbcTemplate.update("DELETE FROM member WHERE email LIKE '%@dummy.tasteam.kr'");
	}

	// ── COUNT ─────────────────────────────────────────────────────────────────

	public long countMembers() {
		return query("SELECT COUNT(*) FROM member WHERE deleted_at IS NULL");
	}

	public long countRestaurants() {
		return query("SELECT COUNT(*) FROM restaurant WHERE deleted_at IS NULL");
	}

	public long countGroups() {
		return query("SELECT COUNT(*) FROM \"group\" WHERE deleted_at IS NULL");
	}

	public long countSubgroups() {
		return query("SELECT COUNT(*) FROM subgroup WHERE deleted_at IS NULL");
	}

	public long countReviews() {
		return query("SELECT COUNT(*) FROM review WHERE deleted_at IS NULL");
	}

	public long countChatMessages() {
		return query("SELECT COUNT(*) FROM chat_message WHERE deleted_at IS NULL");
	}

	public long countNotifications() {
		return query("SELECT COUNT(*) FROM notification");
	}

	public long countFavorites() {
		return query("SELECT COUNT(*) FROM member_favorite_restaurant WHERE deleted_at IS NULL");
	}

	// ── helpers ───────────────────────────────────────────────────────────────

	/**
	 * 명시적 시퀀스(member_seq 등)에서 count개의 ID를 한 번에 선점한다.
	 * INSERT에서 RETURNING id를 제거하고 jdbcTemplate.update()만 사용할 수 있게 한다.
	 */
	private List<Long> preallocateIds(String sequenceName, int count) {
		String sql = "SELECT nextval('" + sequenceName + "') FROM generate_series(1, ?)";
		return jdbcTemplate.queryForList(sql, Long.class, count);
	}

	/**
	 * GENERATED BY DEFAULT AS IDENTITY 컬럼의 내부 시퀀스에서 count개의 ID를 한 번에 선점한다.
	 * pg_get_serial_sequence로 시퀀스 이름을 카탈로그에서 조회한다.
	 */
	private List<Long> preallocateIdentityIds(String tableName, int count) {
		String sql = "SELECT nextval(pg_get_serial_sequence('" + tableName + "', 'id')) FROM generate_series(1, ?)";
		return jdbcTemplate.queryForList(sql, Long.class, count);
	}

	private Timestamp ts() {
		return Timestamp.from(Instant.now());
	}

	private long query(String sql) {
		Long result = jdbcTemplate.queryForObject(sql, Long.class);
		return result != null ? result : 0L;
	}
}
